# Generated by Django 6.1.2 on 2026-10-08 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('DEPOSITED', 'Deposited'), ('RECONCILED', 'Reconciled')], default='COLLECTED', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_collections', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='customers.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='loans.loan')),
            ],
        ),
    ]
