# Generated by Django 6.1.2 on 2026-10-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposits', '0001_initial'),
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdeposit',
            name='reconciliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposits', to='reconciliation.reconciliation'),
        ),
    ]
