# Generated by Django 6.1.2 on 2026-10-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_remove_bankdeposit_branch_and_more'),
        ('settlements', '0002_alter_settlement_bank_deposit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankDeposit',
        ),
    ]
